
export enum team {
    FIND_ALL_TEAMS="FIND_ALL_TEAMS",
    SAVE_TEAM="SAVE_TEAM",
    DELETE_TEAM="DELETE_TEAM"
}

export enum player {
    FIND_ALL_PLAYERS="FIND_ALL_PLAYERS",
    SAVE_PLAYER="SAVE_PLAYER",
    DELETE_PLAYER="DELETE_PLAYER"
}